# Generated by Django 4.1.3 on 2022-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cnhs_2', '0004_alter_candidatos_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_cedv',
            field=models.TextField(blank=True, default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, null=True, verbose_name='Justificativa para fins de auditoria'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_cnh',
            field=models.TextField(blank=True, default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, null=True, verbose_name='Justificativa para fins de auditoria'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_crt',
            field=models.TextField(blank=True, default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, null=True, verbose_name='Justificativa para fins de auditoria'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_jm',
            field=models.TextField(blank=True, default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, null=True, verbose_name='Justificativa para fins de auditoria'),
        ),
    ]
