# Generated by Django 4.1.3 on 2022-11-09 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_cnhs_2', '0005_alter_candidatos_justificativas_auditoria_cedv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de criação do registro'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_cedv',
            field=models.TextField(default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, verbose_name='Justificativa para fins de auditoria'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_cnh',
            field=models.TextField(default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, verbose_name='Justificativa para fins de auditoria'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_crt',
            field=models.TextField(default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, verbose_name='Justificativa para fins de auditoria'),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='justificativas_auditoria_jm',
            field=models.TextField(default='Correção não realizada.', help_text='obs*: Limpe a caixa de texto acima e justifique o motivo da correção!', max_length=240, verbose_name='Justificativa para fins de auditoria'),
        ),
    ]
