# Generated by Django 4.1.3 on 2022-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cnhs_2', '0006_alter_candidatos_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='nome',
            field=models.CharField(help_text='Completo e em caixa alta, sem abreviações*', max_length=100, null=True, verbose_name='Nome do(a) Candidato(a)'),
        ),
    ]
