# Generated by Django 4.1.3 on 2022-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cnhs_2', '0007_alter_candidatos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='categoria_cnh',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Categoria CNH Solici.'),
        ),
    ]
