# Generated by Django 4.1.3 on 2022-11-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_cnhs_2', '0008_alter_candidatos_categoria_cnh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatos',
            options={'permissions': [('pode_manipular_cnh', 'pode manipular cnh'), ('pode_manipular_jm', 'pode manipular jm'), ('pode_manipular_crt', 'pode manipular crt'), ('pode_manipular_cedv', 'pode manipular cedv')], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
    ]
